sudo: required
services:
    - docker

before_install:
  - docker build -t victoramaya/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true victoramaya/docker-react npm run test -- --coverage